stages:
  - deploy

deploy-railway:
  stage: deploy
  image: ubuntu
  only:
    - master
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh
    - railway up --service=$RAILWAY_SERVICE_NAME -d