image: gradle:6.8.3-jdk11

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - deploy

deploy-railway:
  stage: deploy
  image: ubuntu
  only:
    - development
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - railway link e0ce4af9-72ef-4f47-a7b4-e06dfdc5e871 --environment=production
    - railway up --service=$RAILWAY_SERVICE_NAME -d